### ISSUE TITLE
Single Marketplace version

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/vscode-parinfer#12]
@joaomoreno @narma Thanks for starting the Parinfer extension for VS Code!  Unfortunately there are three packages called "Parinfer" in the marketplace now since it changed hands twice.  To avoid confusion, could you unpublish your versions?

I think this will work:

```
vsce unpublish <username>.vscode-parinfer
```

or unpublish from here https://marketplace.visualstudio.com/manage:

<img width="459" alt="screen shot 2017-01-05 at 11 36 27 pm" src="https://cloud.githubusercontent.com/assets/116838/21708623/40464e38-d3a0-11e6-8a5a-3983978d9042.png">

**Comment by joaomoreno** [comment]
Done!

**Comment by shaunlebron** [comment]
thanks!

@narma (friendly bump, when you get a chance)

**Comment by narma** [comment]
Oh, sorry! Didn't notice notification.

Done! //cc @shaunlebron

**Comment by shaunlebron** [comment]
thanks!
