### ISSUE TITLE
Not working with lisp (or anything other than clojure language)

### ISSUE THREAD

**Issue by sudodoki** [oakmac/vscode-parinfer#15]
Thanks for the plugin. I'm not directly reporting issue, but *possible issue* and the way I solved it. Maybe, you know how to do it better.

AFAIR right now due to [activationEvents](https://github.com/shaunlebron/vscode-parinfer/blob/master/package.json#L16) parinfer would be only available for clojure files. but you could stick `"parinfer.activationEvents": ["onLanguage:lisp", "onLanguage:clojure"]` in your user's settings to make it work for both (I still need to toggle mode when opening lisp files for parinfer to start for some reason).

**Comment by sudodoki** [comment]
No, I probably was messing way to long with editor and at that point broke something or made a mistake of switching syntax. This seems not to be working for me now and based on https://github.com/shaunlebron/vscode-parinfer/blob/master/package.json#L20 I don't think I would be able to override it from user settings. 🤔 So I still don't know a proper solution for this.

**Comment by shaunlebron** [comment]
Thanks for filing this!  sorry for late reply

Would it be sufficient to just add more languages to the default activationEvents?

**Comment by shaunlebron** [comment]
Fixed in v0.6.1

**Comment by sudodoki** [comment]
Thanks so much, it works now.
