### ISSUE TITLE
Does not properly detect ending paren in Racket

### ISSUE THREAD

**Issue by chrisdavies** [oakmac/vscode-parinfer#17]
Given the following racket code, parinfer keeps dropping the trailing ')'. This makes me sad. :/

```rkt
(define (tokenize str)
  (filter-not (lambda (s) (or (equal? s "") (equal? (substring s 0 1) ";")))
    (regexp-match* #px"[\\s,]*(~@|[\\[\\]{}()'`~^@]|\"(?:\\\\.|[^\\\\\"])*\"|;.*|[^\\s\\[\\]{}('\"`,;)]*)"
                   "hello, world!"))))
```

P.S. Parenfer is *great*. Thank you for it!

**Comment by chrisdavies** [comment]
By the way, is there a way to turn parinfer off for a specific block of code? e.g. something like `; parinfer ignore` or something?

**Comment by chrisdavies** [comment]
Er... Seems parinfer is right. It's a different plugin that's making the parens appear to not match.

**Comment by shaunlebron** [comment]
Hello, thanks for filing!

It looks like there should only be three parens `)))` not four `))))` at the end, right?

The regex is probably confusing another parser, but it looks like Parinfer is handling it well.

And sorry, parinfer has to run on a whole file currently.
