### ISSUE TITLE
dim trailing close parens in Indent or Smart mode

### ISSUE THREAD

**Issue by oakmac** [oakmac/vscode-parinfer#25]
[Atom parinfer](https://github.com/oakmac/atom-parinfer) has this feature enabled through some [slick CSS](https://github.com/oakmac/atom-parinfer/blob/master/styles/atom-parinfer.less#L23-L27).

Would be nice to have this feature in vscode-parinfer.

**Comment by oakmac** [comment]
Did some research on this. These links might be helpful:

* https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentColorProvider
* https://code.visualstudio.com/docs/getstarted/theme-color-reference#_editor-colors
* https://github.com/tonsky/clojure-warrior/blob/master/src/extension.ts
* https://github.com/Microsoft/vscode-extension-samples/blob/master/decorator-sample/src/extension.ts
* https://github.com/Microsoft/vscode-extension-samples/issues/22#issuecomment-321555992

**Comment by shaunlebron** [comment]
fixed in #31
