### ISSUE TITLE
Performance issues on large files

### ISSUE THREAD

**Issue by oakmac** [oakmac/vscode-parinfer#4]
I noticed some poor performance when using this extension on large files. For some files the extension is basically unusable due to how long it takes to process.

When I was developing [atom-parinfer](https://github.com/oakmac/atom-parinfer), I tested against [cljs.core](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs) - which has over 10k lines. Had to come up with some performance hacks to improve Parinfer performance for that threshold.

Mainly:
1) Only sending the code that had likely changed to Parinfer instead of the whole file. See: [this code](https://github.com/oakmac/atom-parinfer/blob/master/src-cljs/atom_parinfer/core.cljs#L184-L214) as well as [Issue #9](https://github.com/oakmac/atom-parinfer/issues/9)
2) The use of a small [LRU cache](https://github.com/oakmac/atom-parinfer/blob/master/src-cljs/atom_parinfer/core.cljs#L179-L182) to prevent repeated processing.

I'm not sure these are perfect solutions and @shaunlebron has expressed improving performance in the main Parinfer algorithm, but these tricks might be helpful in the meantime.

**Comment by oakmac** [comment]
Since this issue was opened, [parinfer.js](https://github.com/shaunlebron/parinfer/tree/master/lib) has been re-written and is substantially faster than the implementation currently being used for this plugin.

atom-parinfer still uses the "parent expression" performance hack described [here](https://github.com/oakmac/atom-parinfer#known-limitations), although to be honest I'm not sure this is even necessary anymore. Either way, there have been zero complaints from users about speed issues.

FYI

**Comment by shaunlebron** [comment]
fixed by https://github.com/shaunlebron/vscode-parinfer/pull/10
