### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by draugnim** [oakmac/vscode-parinfer#8]
I really would appreciate if someone could give me some installation instrucitions.

**Comment by joaomoreno** [comment]
In Code, open the command palette with `Ctrl Shift P`, search for `Extensions: Install Extension`, search for `parinfer`, install it.

**Comment by draugnim** [comment]
Thanks. Is it possible to install the extension in Visual Studio Community 2015 ?

**Comment by joaomoreno** [comment]
No, this is a [Visual Studio **Code**](https://code.visualstudio.com/) extension only.
