### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by oakmac** [oakmac/vscode-parinfer#9]
I'm curious about the future of this project / repo. As of Aug 2016, I see several months-old unmerged pull requests and no commit activity since Nov 2015.

[parinfer.js](https://github.com/shaunlebron/parinfer/tree/master/lib) has advanced substantially since it's initial release last year. I would love to see this project reflect those improvements and help draw Clojure(Script) / Lisp developers to VS Code. For reference, atom-parinfer has seen [over 10,000 downloads](https://atom.io/packages/parinfer) since it's initial launch.

What are your plans for this project? Is there anything I can do to help advance this plugin?

**Comment by joaomoreno** [comment]
I started this as a sample project when VS Code came out with extension support. The lack of support stems from the fact that I don't code in Lisp at all. Unfortunately I let those PRs fly by and because of that there is already another extension in the Marketplace:

![image](https://cloud.githubusercontent.com/assets/22350/17959316/e3ec9732-6a9f-11e6-9a77-4cd37ad9c9c8.png)

This fork, by @narma, already seems to have the latest version from parinfer. Given the fact that @narma and you seem passionate about it, I'd gladly remove my extension from the Marketplace, close this repository and let you guys run a fork of it as the main project.

What do you say?

**Comment by narma** [comment]
Works for me :)

**Comment by shaunlebron** [comment]
@joaomoreno Things like stars and watchers aren't carried over!  Could you merge @narma's changes upstream and transfer ownership rather than closing the repo?

**Comment by oakmac** [comment]
> I'd gladly remove my extension from the Marketplace, close this repository and let you guys run a fork of it as the main project.

This seems like a simple path forward.

re: @shaunlebron: Losing GitHub stars and watchers (and losing the Microsoft name from this repo) are downsides to this approach, but I think install base is probably the more important concern. From the screenshot above, @narma's fork already has a sizeable lead over this repo.

**Comment by shaunlebron** [comment]
To save the stars/watchers, just transfer ownership at the bottom of the settings menu for the repo.  That will move the repo from Microsoft's github org to narma's account:

<img width="781" alt="screen shot 2016-08-25 at 9 58 32 pm" src="https://cloud.githubusercontent.com/assets/116838/17992682/33de872c-6b0f-11e6-9b31-0e7259b68f82.png">

**Comment by joaomoreno** [comment]
Yeah let's
1. Transfer the repository
2. Remove `joaomoreno.parinfer` from the Marketplace

That way you guys keep both the Github and Marketplace stardom.

Thanks a lot for picking it up!

**Comment by joaomoreno** [comment]
Got two errors:

> narma/vscode-parinfer already exists and You can only transfer a repository from an organization to yourself at this time

The first seems easy to fix; the second not so much. So, we'll just have to close this repo, agree?

**Comment by shaunlebron** [comment]
You can transfer to yourself and then to narma.  But @narma will have to delete or rename his fork before the transfer.

**Comment by joaomoreno** [comment]
Cool, did the first move. Waiting on @narma.

**Comment by narma** [comment]
@joaomoreno Done!

**Comment by joaomoreno** [comment]
And done!

**Comment by narma** [comment]
@joaomoreno I don't see any changes

**Comment by shaunlebron** [comment]
yeah, still on your account @joaomoreno: https://github.com/joaomoreno/vscode-parinfer

**Comment by narma** [comment]
Oh, my bad. Didn't noticed email from github. It's done.
